language: java
dist: trusty
after_success:
  - if [[ "$TRAVIS_BRANCH" == "3.0" && "$TRAVIS_PULL_REQUEST" = "false" ]]; then 
    mvn deploy -Dmaven.test.skip=true --settings settings.xml;
    mvn deploy -Dmaven.test.skip=true -Pdocker --settings settings.xml;
    fi
addons:
  hostname: short-hostname
services:
  - docker
jdk:
  - oraclejdk8
notifications:
  email: false
